- id: '1619623682098'
  alias: 'Backup Fehler '
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.snapshots_stale
    from: 'off'
    to: 'on'
  condition: []
  action:
  - data:
      title: 'Googledrive Backup Fehler '
      message: 'Fehler beheben '
    action: notify.notify
  mode: single
- id: '1620231491485'
  alias: Alfred benötigt Hilfe
  description: ''
  trigger:
  - platform: state
    entity_id:
    - vacuum.alfred
    from: cleaning
    to: error
  condition: []
  action:
  - data:
      title: Alfred braucht Hilfe
      message: Alfred Steckt fest oder braucht Hilfe beim Reinigen
    action: notify.notify
  mode: single
- id: '1620671396281'
  alias: TV und Licht anschalten
  description: ''
  trigger:
  - platform: device
    device_id: 4dc36994073ce42f196689addbcaeede
    domain: media_player
    entity_id: media_player.65pus8507_12_2
    type: turned_on
  condition:
  - condition: or
    conditions:
    - condition: sun
      after: sunset
    - condition: sun
      before: sunrise
  action:
  - scene: scene.tv_licht
  mode: single
- id: '1620854843377'
  alias: 'TV Licht auschalten '
  description: ''
  triggers:
  - device_id: 4dc36994073ce42f196689addbcaeede
    domain: media_player
    entity_id: media_player.65pus8507_12_2
    type: turned_off
    trigger: device
  - trigger: state
    entity_id:
    - sun.sun
    to: above_horizon
  conditions: []
  actions:
  - scene: scene.tv_licht_aus
  mode: single
- id: '1622209039392'
  alias: 'Alfred reinigen  '
  description: ''
  trigger:
  - platform: time
    at: '19:00'
  condition:
  - condition: template
    value_template: '{{ now().day == 20 }}'
  action:
  - data:
      title: 'Alfred reinigen '
      message: 'Alfred von Haaren an den Rollen befreien und Sensoren reinigen '
    action: notify.notify
  mode: single
- id: '1629961083917'
  alias: 'Waschmaschine ist fertig '
  description: ''
  triggers:
  - entity_id: timer.baumwolle_60deg
    from: active
    to: idle
    trigger: state
  - entity_id: timer.waschen_hemden_40degc
    from: active
    to: idle
    trigger: state
  - entity_id: timer.waschen_pflegeleicht_plus_30degc
    from: active
    to: idle
    trigger: state
  - entity_id: timer.waschen_sport_30degc
    from: active
    to: idle
    trigger: state
  - entity_id: timer.waschen_wolle_30degc
    from: active
    to: idle
    trigger: state
  - entity_id:
    - timer.waschen_pflegeleicht_40degc
    trigger: state
  conditions: []
  actions:
  - parallel:
    - metadata: {}
      data:
        title: Waschmaschine ist fertig
        message: Wäsche kann aufgehängt werden
      action: notify.mobile_app_iphone_von_julia
    - action: notify.mobile_app_benehandy
      metadata: {}
      data:
        message: Wäsche kann aufgehängt werden
        title: Waschmaschine
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: media_player.wohnzimmer
          state: 'off'
        - condition: state
          entity_id: media_player.wohnzimmer
          state: idle
        - condition: state
          entity_id: media_player.wohnzimmer
          state: paused
      sequence:
      - type: turn_on
        device_id: b2227f95cd200e6eb95585d9dca557f6
        entity_id: e936d41a775b260a5f23b2ff9fdf6dfe
        domain: switch
      - metadata: {}
        data:
          cache: true
          media_player_entity_id: media_player.wohnzimmer
          message: Die Waschmaschine ist fertig
        target:
          entity_id: tts.piper
        action: tts.speak
      - type: turn_off
        device_id: b2227f95cd200e6eb95585d9dca557f6
        entity_id: e936d41a775b260a5f23b2ff9fdf6dfe
        domain: switch
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: media_player.wohnzimmer
          state: 'on'
        - condition: state
          entity_id: media_player.wohnzimmer
          state: playing
      sequence:
      - metadata: {}
        data: {}
        target:
          entity_id: media_player.wohnzimmer
        action: media_player.media_pause
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - type: turn_on
        device_id: b2227f95cd200e6eb95585d9dca557f6
        entity_id: e936d41a775b260a5f23b2ff9fdf6dfe
        domain: switch
      - metadata: {}
        data:
          cache: true
          media_player_entity_id: media_player.wohnzimmer
          message: Die Waschmaschine ist fertig
        target:
          entity_id: tts.piper
        action: tts.speak
      - type: turn_off
        device_id: b2227f95cd200e6eb95585d9dca557f6
        entity_id: e936d41a775b260a5f23b2ff9fdf6dfe
        domain: switch
      - delay:
          hours: 0
          minutes: 0
          seconds: 10
          milliseconds: 0
      - metadata: {}
        data: {}
        target:
          entity_id: media_player.wohnzimmer
        action: media_player.media_play
  mode: single
- id: '1649874529226'
  alias: TV Licht bei Sonnenuntergang
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition:
  - condition: device
    device_id: 4dc36994073ce42f196689addbcaeede
    domain: media_player
    entity_id: media_player.65pus8507_12_2
    type: is_on
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.tv_licht
    metadata: {}
  mode: single
- id: '1660470758049'
  alias: Wasserfilter Datum Heute
  description: ''
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: wasser_filter_gewechselt
  condition: []
  action:
  - service: input_datetime.set_datetime
    data:
      date: '{{ as_timestamp(now())|timestamp_custom(''%Y-%m-%d'') }}'
    entity_id: input_datetime.wasser_filter_gewechselt
  mode: single
- id: '1667023100430'
  alias: Wasserfilter Wechsel
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.wasser_filter_verbliebene_zeit
    from: '1'
    to: '0'
  condition: []
  action:
  - data:
      title: Wasserfilter heute Wechseln
      message: 2x spülen danach nutzen
    action: notify.notify
  mode: single
- id: '1670681858395'
  alias: PC Licht bei Sonnenuntergang
  description: ''
  triggers:
  - event: sunset
    offset: 0
    trigger: sun
  conditions: []
  actions:
  - target:
      entity_id: scene.gaming
    metadata: {}
    action: scene.turn_on
    data: {}
  mode: single
- id: '1670681939371'
  alias: PC und Licht anschalten
  description: ''
  triggers: []
  conditions:
  - condition: sun
    before: sunrise
    after: sunset
  actions:
  - target:
      entity_id: scene.gaming
    metadata: {}
    action: scene.turn_on
    data: {}
  mode: single
- id: '1670681974598'
  alias: PC Licht ausschalten
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sun.sun
    to: above_horizon
  conditions: []
  actions:
  - target:
      entity_id: scene.gaming_licht_aus
    metadata: {}
    action: scene.turn_on
    data: {}
  mode: single
- id: '1682763613807'
  alias: Kontaktlinsen wechseln
  description: ''
  triggers:
  - entity_id:
    - input_number.kontaktlinsen
    enabled: true
    trigger: state
  conditions:
  - condition: template
    value_template: '{{ state_attr(''input_number.kontaktlinsen'', ''max'')|float(0)
      == states(''input_number.kontaktlinsen'')|float(0) }}'
    enabled: true
  actions:
  - data:
      value: 0
    target:
      entity_id: input_number.kontaktlinsen
    action: input_number.set_value
  - action: notify.mobile_app_benehandy
    data:
      title: Kontaktlinsen wechsel
  mode: single
- id: '1684962963899'
  alias: Benachrichtigung Pollenbelastung Graeser
  description: ''
  triggers:
  - at: 07:00:00
    trigger: time
  conditions:
  - condition: numeric_state
    entity_id: sensor.dwd_pollen_graeser
    attribute: today
    above: 0
  actions:
  - data:
      title: Achtung Gräserpollen Belastung ist
      message: '{% if state_attr(''sensor.dwd_pollen_graeser'',''today'') == 6 %}  übertrieben
        hoch  {% elif state_attr(''sensor.dwd_pollen_graeser'',''today'') == 5 %}  sehr
        hoch  {% elif state_attr(''sensor.dwd_pollen_graeser'',''today'') == 4 %}
        hoch {% elif state_attr(''sensor.dwd_pollen_graeser'',''today'') == 3 %}  mittel  {%
        elif state_attr(''sensor.dwd_pollen_graeser'',''today'') == 2 %}  niedrig  {%
        elif state_attr(''sensor.dwd_pollen_graeser'',''today'') == 1 %} sehr niedrig     {%
        else %} nicht vorhanden {% endif %}'
    action: notify.mobile_app_benehandy
  mode: single
- id: '1700080552074'
  alias: Update notifications
  description: ''
  use_blueprint:
    path: mdegat01/update_notifications.yaml
    input:
      update_entities:
      - update.aircast_update
      - update.airsonos_update
      - update.calibre_update
      - update.cloudflared_update
      - update.emqx_update
      - update.home_assistant_core_update
      - update.grafana_update
      - update.home_assistant_google_drive_backup_update
      - update.home_assistant_operating_system_update
      - update.home_assistant_supervisor_update
      - update.mariadb_update
      - update.matter_server_update
      - update.openwakeword_update
      - update.piper_update
      - update.pgadmin4_update
      - update.samba_share_update
      - update.spotify_connect_update
      - update.tandoor_recipes_update
      - update.studio_code_server_update
      - update.timescaledb_update
      - update.vaultwarden_bitwarden_update
      - update.whisper_update
      - update.terminal_ssh_update
      - update.auto_entities_update
      - update.bar_card_update
      - update.browser_mod_update
      - update.button_card_update
      - update.calibre_web_update
      - update.card_mod_update
      - update.datetime_card_update
      - update.deutscher_wetterdienst_update
      - update.flipdown_timer_card_update
      - update.govee_lan_control_update
      - update.govee_update
      - update.ha_dashboard_update
      - update.hacs_update
      - update.hass_hue_icons_update
      - update.hass_agent_update
      - update.layout_card_update
      - update.light_entity_card_update
      - update.ltss_update
      - update.mini_media_player_update
      - update.mini_graph_card_update
      - update.my_cards_bundle_update
      - update.philips_tv_remote_update
      - update.simple_weather_card_update
      - update.spotcast_update
      - update.state_switch_update
      - update.team_tracker_card_update
      - update.team_tracker_update
      - update.ui_lovelace_minimalist_update
      - update.watchman_update
      - update.weather_radar_card_update
      - update.ytube_music_player_update
      mobile_app_device: 9c6f616e77139523b879c5204d62a9bd
      send_to_ha: true
      take_backup: false
      only_after: 07:00:00
      only_before: '20:00:00'
      mobile_app_device_2: 61b8611d91abdf0795a0ba6976603fac
- id: '1705495382555'
  alias: Batteries low notification
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      threshold: 10
      time: '17:00:00'
      exclude:
        entity_id:
        - sensor.alfred_batterie
        - sensor.iphone_von_julia_battery_level
        - sensor.benehandy_battery_level
      actions:
      - metadata: {}
        data:
          message: '{{sensors}}'
        action: notify.notify
- id: '1709099857571'
  alias: tägliches Staubsaugen
  description: ''
  trigger:
  - platform: time
    at: '10:00:00'
  condition:
  - condition: and
    conditions:
    - condition: not
      conditions:
      - condition: state
        entity_id: person.benedikt
        state: home
    - condition: not
      conditions:
      - condition: state
        entity_id: person.julia
        state: home
    enabled: true
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - fri
    - thu
  action:
  - service: vacuum.start
    metadata: {}
    data: {}
    target:
      device_id: 57586eb91c79551e919a2a78245134c3
  mode: single
- id: '1720628375647'
  alias: Staubbehälter leeren
  description: ''
  trigger:
  - type: turned_on
    platform: device
    device_id: 57586eb91c79551e919a2a78245134c3
    entity_id: b6ff7b2a4729350493dff89a80b47fc5
    domain: binary_sensor
  condition: []
  action:
  - service: notify.notify
    metadata: {}
    data:
      message: 'Alfred sein Staubbehälter ist voll;  bitte leeren '
      title: Staubbehälter voll!
  - repeat:
      sequence:
      - delay:
          hours: 3
          minutes: 0
          seconds: 0
          milliseconds: 0
      - service: notify.notify
        metadata: {}
        data:
          message: 'Alfred sein Staubbehälter ist voll;  bitte leeren '
          title: Staubbehälter voll!
      until:
      - type: is_off
        condition: device
        device_id: 57586eb91c79551e919a2a78245134c3
        entity_id: b6ff7b2a4729350493dff89a80b47fc5
        domain: binary_sensor
  mode: single
- id: '1721680899386'
  alias: System Set Default Theme
  description: ''
  use_blueprint:
    path: ui_lovelace_minimalist/set_theme.yaml
    input:
      theme: minimalist-mobile
      mode: dark
- id: '1729966558106'
  alias: Weather forecast notification
  description: ''
  use_blueprint:
    path: milperks/weather_notification.yaml
    input:
      weather_entity: weather.gruendau_breitenborn
      notify_device:
      - 9c6f616e77139523b879c5204d62a9bd
      - 61b8611d91abdf0795a0ba6976603fac
      time: 07:00:00
      notify_message:
      - condition
      - temperature
      - precipitation
      - wind
